server.port=8081

basyx.environment=file:/app/runtime/Embolsadora_runtime.xml

basyx.cors.allowed-origins=http://localhost:3000,http://192.168.1.118:3000
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
basyx.cors.allowed-headers=*
