services:
  app:
    image: ghcr.io/agustin-aicardi/proyecto-embolsadora:latest
    container_name: aas_historian_middleware
    restart: unless-stopped
    working_dir: /app
    command: python3 -m src.historian.main
    environment:
      - PYTHONUNBUFFERED=1
      - MODBUS_HOST=plc        # Usamos el contenedor simulador
      - MODBUS_PORT=502
      - POLL_INTERVAL=5
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=NsOYnjYTJswlFmyQtatUtDosZEgN1Oq_gToLHfjcBNr9w-VePHausBAOtCNS3uf_LRKGVkjXe_v8burMDegArQ==
      - INFLUX_ORG=org
      - INFLUX_BUCKET=bucket
    volumes:
      - ./src/historian/tags.yaml:/app/src/historian/tags.yaml:ro
    depends_on:
      - influxdb
      - plc
    networks:
      - pe_net

  plc:
    image: ghcr.io/agustin-aicardi/proyecto-embolsadora:latest
    container_name: modbus_plc_sim
    restart: unless-stopped
    working_dir: /app
    command: python3 -m src.historian.mock_modbus
    networks:
      - pe_net

  influxdb:
    image: influxdb:2.6
    container_name: proyecto-embolsadora-influxdb-1
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - pe_net

networks:
  pe_net:
    driver: bridge

volumes:
  influxdb_data: